@startuml

<style>
    package {
        backgroundcolor #CCC
        Shadowing 1
    }
    document {
        backgroundcolor #949494
    }
    frame {
        backgroundcolor #EEE
    }
    database {
        backgroundcolor #A5CEF0
    }
    queue {
        backgroundcolor #F78F8F
    }
    actor {
        linethickness 3
        linecolor #2B2B2B
    }
    arrow {
        linethickness 2
        linecolor #2B2B2B
    }
    folder {
        backgroundcolor #FFCD73
    }
</style>

package "notifier" {
    frame notifier_api as "API" {
    }
    frame notifier_formatter as "formatter" {
    }
    frame notifier_email_handler as "email_handler" {
    }
    database notifier_postgres as "notifications" {
    }
    queue notifier_queue as "rabbit" {
    }
}

package events as "app events" {
    queue events_kafka as "kafka" {
    }
}

package "auth" {
    frame auth_api as "API" {
    }
}

package "frontend" {
    frame frontend_app as "any JS app" {
    }
}

rectangle notifier_to_events_consumer as "standalone\n consumer"
actor notifier_user as "manager"

events_kafka --> notifier_to_events_consumer
notifier_to_events_consumer --> notifier_api

notifier_user -right-> frontend_app
frontend_app --> notifier_api
frontend_app -right-> events_kafka

notifier_api --> notifier_postgres
notifier_api ---> notifier_queue

notifier_formatter <--> notifier_queue
notifier_email_handler <--> notifier_queue

notifier_formatter <--up-> auth_api
notifier_formatter --> notifier_postgres


@enduml
